# Generated by Django 5.0.1 on 2024-01-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('message_type', models.CharField(default='Message', max_length=15)),
                ('chat_id', models.IntegerField()),
                ('file_id', models.CharField(default=0, max_length=255)),
                ('message_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('status', models.CharField(default=None, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('chat_link', models.CharField(max_length=255)),
                ('chat_id', models.IntegerField()),
            ],
        ),
    ]
