# Generated by Django 5.0.1 on 2024-01-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
