# Generated by Django 5.0.1 on 2024-01-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_botuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='real_status',
            field=models.BooleanField(default=False),
        ),
    ]
