# Generated by Django 5.0.1 on 2024-01-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_botuser_real_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmessage',
            name='chat_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutmessage',
            name='file_id',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aboutmessage',
            name='message_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='aboutmessage',
            name='message_type',
            field=models.CharField(blank=True, default='Message', max_length=15),
        ),
    ]
