# Generated by Django 5.0.1 on 2024-01-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_real_status_botuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmessage',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
