# Generated by Django 5.0.1 on 2024-01-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_aboutmessage_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('message_type', models.CharField(blank=True, default='Message', max_length=15)),
                ('chat_id', models.IntegerField(blank=True)),
                ('file_id', models.CharField(blank=True, default=0, max_length=255)),
                ('answer', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
