# Generated by Django 5.0.1 on 2024-01-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_channelmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelmessage',
            name='chat_id',
            field=models.IntegerField(default=0),
        ),
    ]
