# Generated by Django 5.0.1 on 2024-01-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_channelmessage_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group_link', models.CharField(max_length=255)),
                ('group_id', models.IntegerField()),
            ],
        ),
    ]
