# Generated by Django 5.0.1 on 2024-01-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='GroupBot',
        ),
    ]
