# Generated by Django 5.0.1 on 2024-01-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_rename_group_groupbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelbot',
            name='chat_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='groupbot',
            name='group_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
