# Generated by Django 5.0.1 on 2024-01-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_channelbot_chat_link_alter_groupbot_group_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbot',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
