# Generated by Django 5.0.1 on 2024-01-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_groupbot_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupbot',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
