# Generated by Django 5.0.1 on 2024-01-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_rename_isactive_groupbot_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmessage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
