# Generated by Django 5.0.1 on 2024-01-29 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_aboutmessage_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='is_subcribe',
            field=models.BooleanField(default=False),
        ),
    ]
