# Generated by Django 5.0.1 on 2024-01-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_botuser_is_subcribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutmessage',
            name='auto_answer',
            field=models.TextField(default=''),
        ),
    ]
