# Generated by Django 5.0.1 on 2024-01-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_aboutmessage_auto_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='aboutmessage',
            name='auto_answer',
        ),
    ]
