# Generated by Django 5.0.1 on 2026-06-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_autoanswer_remove_aboutmessage_auto_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('address', models.CharField(blank=True, max_length=512)),
                ('geo_lat', models.FloatField(blank=True, null=True)),
                ('geo_long', models.FloatField(blank=True, null=True)),
                ('phones', models.CharField(blank=True, max_length=255)),
                ('working_hours', models.CharField(blank=True, max_length=512)),
                ('days_off', models.CharField(blank=True, max_length=255)),
                ('extra_notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('specialty', models.CharField(blank=True, max_length=255)),
                ('schedule_text', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=512)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='UZS', max_length=8)),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
