# Generated by Django 5.0.1 on 2026-06-04 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_conversation_conversationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False)),
                ('model_name', models.CharField(default='gpt-4o', max_length=64)),
                ('temperature', models.FloatField(default=0.3)),
                ('confidence_threshold', models.FloatField(default=0.6)),
                ('max_history_messages', models.PositiveIntegerField(default=12)),
                ('max_input_chars', models.PositiveIntegerField(default=2000)),
                ('max_output_tokens', models.PositiveIntegerField(default=500)),
                ('daily_call_cap', models.PositiveIntegerField(default=1500)),
                ('holding_message', models.TextField(default='Savolingiz mutaxassisimizga yuborildi. Tez orada javob beramiz. 🙏')),
                ('persona_extra', models.TextField(blank=True)),
                ('complaint_notify_user_id', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(unique=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIDecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(blank=True)),
                ('kb_version', models.CharField(blank=True, max_length=64)),
                ('intent', models.CharField(blank=True, max_length=64)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=16)),
                ('output_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.conversation')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
