# Generated by Django 5.0.1 on 2026-06-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_aisettings_processedupdate_aidecisionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botuser',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
