# Generated by Django 5.0.1 on 2026-06-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_botuser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmessage',
            name='chat_id',
            field=models.BigIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='channelbot',
            name='chat_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='channelmessage',
            name='chat_id',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='groupbot',
            name='group_id',
            field=models.BigIntegerField(),
        ),
    ]
