# Generated by Django 5.0.1 on 2026-06-04 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_faqsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('post', 'post'), ('article', 'article')], default='post', max_length=16)),
                ('mode', models.CharField(choices=[('ai', 'ai'), ('manual', 'manual')], default='ai', max_length=16)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('reference_link', models.URLField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('generating', 'generating'), ('ready', 'ready'), ('published', 'published'), ('failed', 'failed')], default='draft', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('targets', models.JSONField(blank=True, default=dict)),
                ('publish_results', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.botuser')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
