"""
Django settings for main project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Per-environment config lives in main/.env (one file per machine: dev or prod).
# When no .env is present the defaults below reproduce the original behavior, so
# deploying this to the live prod host without a .env changes nothing.
load_dotenv(BASE_DIR / '.env')

APP_ENV = os.environ.get('APP_ENV', 'prod')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# The default reproduces the original key so an un-configured prod deploy keeps
# its existing signed sessions; set a real SECRET_KEY via .env in every env.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-rut6(^3@i(=u$mq^47o)51ywv*50t(owzvlrsi&47#1xt=8+--',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=False in the prod .env.
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get(
        'ALLOWED_HOSTS', '28ee-84-54-122-156.ngrok-free.app,127.0.0.1'
    ).split(',')
    if h.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pages',
    'django_q',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'main.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Only APP_ENV=prod uses the live db.sqlite3; every other value (e.g. "staging")
# gets an isolated db.dev.sqlite3. APP_ENV defaults to 'prod' (above), so a host
# with no .env still uses the live database.
DB_NAME = os.environ.get(
    'DB_NAME', 'db.sqlite3' if APP_ENV == 'prod' else 'db.dev.sqlite3'
)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / DB_NAME,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Shared, cross-process cache (web process + qcluster worker). DatabaseCache
# avoids Redis; the table is created by `manage.py createcachetable`.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'mehrshifo_cache',
    }
}

# The DatabaseCache table is created by `createcachetable`, not by migrations,
# so it does not exist in the throwaway test DB. Use in-memory cache under tests.
import sys as _sys
if 'test' in _sys.argv:
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}

# Django-Q2 task queue. ORM broker = no Redis. timeout MUST be < retry.
Q_CLUSTER = {
    'name': 'mehrshifo',
    'orm': 'default',
    'workers': 2,
    'timeout': 60,
    'retry': 120,
    'max_attempts': 1,
    'catch_up': False,
    'save_limit': 250,
}
