TOKEN = "5184905704:AAFTNczwSxt-xZD5mtd49NgKtv-J8geDN_o"
URL = "https://1d0f-94-158-59-241.ngrok-free.app/getpost/"
BOT_URL = f"https://api.telegram.org/bot{TOKEN}/"

# {'update_id': 282433149, s
#  'message': {'message_id': 220, 
#              'from': {'id': 1618456770, 
#                       'is_bot': False, 
#                       'first_name': 'Muhammaddiyor', 
#                       'last_name': "O'ktamov", 
#                       'username': 'uktamov_muhammaddiyor', 
#                       'language_code': 'en'}, 
#              'chat': {'id': 1618456770, 
#                       'first_name': 'Muhammaddiyor', 
#                       'last_name': "O'ktamov", 
#                       'username': 'uktamov_muhammaddiyor', 
#                       'type': 'private'}, 
#              'date': 1705583993, 
#              'text': 'hi'}
# }
# {'update_id': 282433154, 
#  'message': {'message_id': 230, 
#              'from': {'id': 1618456770, 
#                       'is_bot': False, 
#                       'first_name': 'Muhammaddiyor', 
#                       'last_name': "O'ktamov", 
#                       'username': 'uktamov_muhammaddiyor', 
#                       'language_code': 'en'}, 
#              'chat': {'id': 1618456770, 
#                       'first_name': 'Muhammaddiyor', 
#                       'last_name': "O'ktamov", 
#                       'username': 'uktamov_muhammaddiyor', 
#                       'type': 'private'}, 
#              'date': 1705586702, 
#              'photo': [{'file_id': 'AgACAgIAAxkBAAPmZakwDtuSXFIfxHIlxckLfm96Q_8AAjDRMRupPEhJ_fBmIYXsJ8MBAAMCAANzAAM0BA', 
#                         'file_unique_id': 'AQADMNExG6k8SEl4', 
#                         'file_size': 1241, 
#                         'width': 80, 
#                         'height': 90},
#                        {'file_id': 'AgACAgIAAxkBAAPmZakwDtuSXFIfxHIlxckLfm96Q_8AAjDRMRupPEhJ_fBmIYXsJ8MBAAMCAANtAAM0BA', 
#                         'file_unique_id': 'AQADMNExG6k8SEly', 
#                         'file_size': 16050, 'width': 285, 'height': 320}, 
#                         {'file_id': 'AgACAgIAAxkBAAPmZakwDtuSXFIfxHIlxckLfm96Q_8AAjDRMRupPEhJ_fBmIYXsJ8MBAAMCAAN4AAM0BA', 
#                          'file_unique_id': 'AQADMNExG6k8SEl9', 'file_size': 67909, 'width': 712, 'height': 800}, 
#                          {'file_id': 'AgACAgIAAxkBAAPmZakwDtuSXFIfxHIlxckLfm96Q_8AAjDRMRupPEhJ_fBmIYXsJ8MBAAMCAAN5AAM0BA', 
#                           'file_unique_id': 'AQADMNExG6k8SEl-', 'file_size': 138947, 'width': 1139, 'height': 1280}], 
#                           'caption': '⌨️ HP Victus Gaming \n\xa0 \n➡️ Protsessor\n💬 Core i5 12450H [ 12-avlod ]\n💬 [2.0GHz ~ 4.40GHz] 8 yader 12 potok\n\n➡️ Tezkor xotira\n🟡 DDR4 16GB \n\n➡️ Videokarta 2ta\n💬 Nvidia Geforce GTX 1650 4GB \n💬 Intel UHD Graphics \n\ n➡️ Xotira\n🟡 512GB M.2 Nvme SSD', 
#                           'caption_entities': [{'offset': 3, 'length': 17, 'type': 'bold'}, 
#                                                {'offset': 27, 'length': 10, 'type': 'bold'}, 
#                                                {'offset': 27, 'length': 10, 'type': 'underline'}, 
#                                                {'offset': 112, 'length': 13, 'type': 'bold'}, 
#                                                {'offset': 112, 'length': 13, 'type': 'underline'}, 
#                                                {'offset': 144, 'length': 11, 'type': 'bold'}, 
#                                                {'offset': 144, 'length': 10, 'type': 'underline'}, 
#                                                {'offset': 155, 'length': 3, 'type': 'bold'}, 
#                                                {'offset': 155, 'length': 3, 'type': 'underline'}, 
#                                                {'offset': 218, 'length': 6, 'type': 'bold'}, 
                                               
#                                                {'offset': 218, 'length': 6, 'type': 'underline'}]}}